// <auto-generated />
using System;
using BitirmeProjem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeProjem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.AIRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AIRecommendations");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MonthlyPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.FinancialProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DebtAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RentExpense")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RentIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FinancialProfiles");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.FinancialScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FinancialScoreHistories");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionTextEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OptionTextTr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("RiskQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskQuestionId");

                    b.ToTable("RiskOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220101"),
                            OptionTextEn = "I sell immediately",
                            OptionTextTr = "Hemen satarım",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220102"),
                            OptionTextEn = "I wait for a while",
                            OptionTextTr = "Bir süre beklerim",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220103"),
                            OptionTextEn = "I consider making additional investments",
                            OptionTextTr = "Ek yatırım yapmayı düşünürüm",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220104"),
                            OptionTextEn = "I think long-term and keep holding",
                            OptionTextTr = "Uzun vadeli düşünür, tutmaya devam ederim",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220201"),
                            OptionTextEn = "Keeping my money safe",
                            OptionTextTr = "Paramın güvende kalması",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220202"),
                            OptionTextEn = "Balanced growth",
                            OptionTextTr = "Dengeli büyüme",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220203"),
                            OptionTextEn = "Achieving high returns",
                            OptionTextTr = "Yüksek getiri elde etmek",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220204"),
                            OptionTextEn = "Taking risks for maximum gain",
                            OptionTextTr = "Maksimum kazanç için risk almak",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220301"),
                            OptionTextEn = "Less than 5%",
                            OptionTextTr = "%5'ten az",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220302"),
                            OptionTextEn = "Between 5% - 15%",
                            OptionTextTr = "%5 - %15 arası",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220303"),
                            OptionTextEn = "Between 15% - 30%",
                            OptionTextTr = "%15 - %30 arası",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220304"),
                            OptionTextEn = "More than 30%",
                            OptionTextTr = "%30'dan fazla",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220401"),
                            OptionTextEn = "Less than 1 year",
                            OptionTextTr = "1 yıldan kısa",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220402"),
                            OptionTextEn = "Between 1-3 years",
                            OptionTextTr = "1-3 yıl arası",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220403"),
                            OptionTextEn = "Between 3-5 years",
                            OptionTextTr = "3-5 yıl arası",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220404"),
                            OptionTextEn = "More than 5 years",
                            OptionTextTr = "5 yıldan uzun",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220501"),
                            OptionTextEn = "I have very little knowledge",
                            OptionTextTr = "Çok az bilgim var",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220502"),
                            OptionTextEn = "I have basic knowledge",
                            OptionTextTr = "Temel seviyede bilgim var",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220503"),
                            OptionTextEn = "I have intermediate knowledge",
                            OptionTextTr = "Orta seviyede bilgim var",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220504"),
                            OptionTextEn = "I have advanced knowledge",
                            OptionTextTr = "İleri seviyede bilgim var",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220601"),
                            OptionTextEn = "Time deposit",
                            OptionTextTr = "Vadeli mevduat",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111106"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220602"),
                            OptionTextEn = "Gold / foreign currency",
                            OptionTextTr = "Altın / döviz",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111106"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220603"),
                            OptionTextEn = "Stock funds",
                            OptionTextTr = "Hisse senedi fonları",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111106"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220604"),
                            OptionTextEn = "Crypto / high-risk investments",
                            OptionTextTr = "Kripto / yüksek riskli yatırımlar",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111106"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220701"),
                            OptionTextEn = "I sell all my investments",
                            OptionTextTr = "Tüm yatırımlarımı satarım",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111107"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220702"),
                            OptionTextEn = "I reduce my risk",
                            OptionTextTr = "Riskimi azaltırım",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111107"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220703"),
                            OptionTextEn = "I monitor the market and wait",
                            OptionTextTr = "Piyasayı takip ederim ve beklerim",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111107"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220704"),
                            OptionTextEn = "I see it as an opportunity and increase investment",
                            OptionTextTr = "Fırsat görüp yatırım artırırım",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111107"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220801"),
                            OptionTextEn = "Very low risk",
                            OptionTextTr = "Çok düşük risk",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111108"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220802"),
                            OptionTextEn = "Controlled risk",
                            OptionTextTr = "Kontrollü risk",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111108"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220803"),
                            OptionTextEn = "Medium-high risk",
                            OptionTextTr = "Orta-yüksek risk",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111108"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220804"),
                            OptionTextEn = "High risk",
                            OptionTextTr = "Yüksek risk",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111108"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220901"),
                            OptionTextEn = "Low but guaranteed return",
                            OptionTextTr = "Düşük ama garanti getiri",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111109"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220902"),
                            OptionTextEn = "Return above inflation",
                            OptionTextTr = "Enflasyon üstü getiri",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111109"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220903"),
                            OptionTextEn = "High growth potential",
                            OptionTextTr = "Yüksek büyüme potansiyeli",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111109"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222220904"),
                            OptionTextEn = "Very high earnings potential",
                            OptionTextTr = "Çok yüksek kazanç ihtimali",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111109"),
                            Score = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221001"),
                            OptionTextEn = "Safety is most important to me",
                            OptionTextTr = "Güvenlik benim için en önemlisi",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111110"),
                            Score = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221002"),
                            OptionTextEn = "I balance risk and security",
                            OptionTextTr = "Risk ve güven arasında denge kurarım",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111110"),
                            Score = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221003"),
                            OptionTextEn = "I can take risks for profit",
                            OptionTextTr = "Kazanç için risk alabilirim",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111110"),
                            Score = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222221004"),
                            OptionTextEn = "High risk doesn't bother me",
                            OptionTextTr = "Yüksek risk beni rahatsız etmez",
                            RiskQuestionId = new Guid("11111111-1111-1111-1111-111111111110"),
                            Score = 4
                        });
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("QuestionTextEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuestionTextTr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrderIndex")
                        .IsUnique();

                    b.ToTable("RiskQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            OrderIndex = 1,
                            QuestionTextEn = "If one of your investments loses 20% of its value in a short time, what would you do?",
                            QuestionTextTr = "Bir yatırımınız kısa sürede %20 değer kaybederse ne yaparsınız?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            OrderIndex = 2,
                            QuestionTextEn = "What is your most important priority when investing?",
                            QuestionTextTr = "Yatırım yaparken en önemli önceliğiniz nedir?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            OrderIndex = 3,
                            QuestionTextEn = "What portion of your monthly income can you set aside for investment?",
                            QuestionTextTr = "Aylık gelirinizin ne kadarını yatırım için ayırabilirsiniz?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            OrderIndex = 4,
                            QuestionTextEn = "How do you think about your investment horizon?",
                            QuestionTextTr = "Yatırım sürenizi nasıl düşünüyorsunuz?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            OrderIndex = 5,
                            QuestionTextEn = "How would you assess your knowledge of financial markets?",
                            QuestionTextTr = "Finansal piyasalardaki bilginizi nasıl değerlendirirsiniz?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            OrderIndex = 6,
                            QuestionTextEn = "Which of the following investment types do you prefer?",
                            QuestionTextTr = "Aşağıdaki yatırım türlerinden hangisini tercih edersiniz?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            OrderIndex = 7,
                            QuestionTextEn = "How would you react in an unexpected economic crisis?",
                            QuestionTextTr = "Beklenmedik bir ekonomik kriz olduğunda nasıl davranırsınız?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            OrderIndex = 8,
                            QuestionTextEn = "How much risk are you willing to take to reach your financial goal?",
                            QuestionTextTr = "Finansal hedefinize ulaşmak için ne kadar risk almaya hazırsınız?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            OrderIndex = 9,
                            QuestionTextEn = "What annual performance of your investment would satisfy you?",
                            QuestionTextTr = "Yatırımınızın yıllık performansı nasıl olursa sizi memnun eder?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            OrderIndex = 10,
                            QuestionTextEn = "Which of the following describes you best?",
                            QuestionTextTr = "Aşağıdakilerden hangisi sizi daha iyi tanımlar?"
                        });
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskTestAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiskOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiskQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiskTestResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RiskOptionId");

                    b.HasIndex("RiskQuestionId");

                    b.HasIndex("RiskTestResultId");

                    b.ToTable("RiskTestAnswers");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MLRiskLevel")
                        .HasColumnType("int");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RiskTestResults");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.AIRecommendation", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.Debt", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.FinancialProfile", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.User", "User")
                        .WithOne("FinancialProfile")
                        .HasForeignKey("BitirmeProjem.Domain.Entities.FinancialProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.FinancialScoreHistory", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.Goal", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskOption", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.RiskQuestion", "RiskQuestion")
                        .WithMany("Options")
                        .HasForeignKey("RiskQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskQuestion");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskTestAnswer", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.RiskOption", "RiskOption")
                        .WithMany()
                        .HasForeignKey("RiskOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BitirmeProjem.Domain.Entities.RiskQuestion", "RiskQuestion")
                        .WithMany()
                        .HasForeignKey("RiskQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BitirmeProjem.Domain.Entities.RiskTestResult", "RiskTestResult")
                        .WithMany("Answers")
                        .HasForeignKey("RiskTestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskOption");

                    b.Navigation("RiskQuestion");

                    b.Navigation("RiskTestResult");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskTestResult", b =>
                {
                    b.HasOne("BitirmeProjem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.RiskTestResult", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("BitirmeProjem.Domain.Entities.User", b =>
                {
                    b.Navigation("FinancialProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
